---
title: 'Setting up the environment'
teaching: 10
exercises: 2
---

## Setting up the environment and photographing

Please [refer to the equipment][setup] that you will need
access to.

You will need to consider the following
camera settings during your acquisition
of photographs:


-	Preferably shoot in RAW and in maximal 
resolution. JPG compression creates noise that should 
be avoided. 
If JPG images are to be used, then prefer 
high quality JPG images.
-	ISO values should be the lowest possible 
as you want clear, sharp images without 
too much noise. ISO 100 will provide good 
pictures without much noise but for this 
you will need a tripod because longer shutter 
speeds will be required. For hand-held camera you 
can go up to ISO 800 but this will bring more 
grain to your pictures.
-	Aperture value (f number) should be high 
enough so as to be able to distinguish details 
without having blurred surfaces. A higher f 
number means that you will get a better depth 
of field.
Something between f/8 and f/16 would work well.
-	Shutter speed should be fast enough to freeze 
images and avoid blur that is caused by the movement 
of the camera. If you are using a tripod you can use 
slower shutter speeds. The rule here is that anything 
below (slower) than 1/60 of a second requires a tripod.

Good focus is important. Be careful to have all the important parts of the image in focus. Automatic focus can be used when you are rotating around the object, but you can set focus manually if you are using a turntable.

### Example of settings

f/8, ISO 400, shutter speed 1/30 and if light is not enough you can increase ISO to 800 OR lower shutter speed to 1/15 (remember that any shutter speed that is lower than 1/60 requires a tripod). 

Please note that these are just examples and you should check exposure for every acquisition depending on current light conditions.


## Acquisition of images

Good acquisition of images is 
important in order to have a 
successful project. 
Please have in mind that the right/optimal setup 
will provide you with the correct dataset that 
will work properly with the software and will 
provide you with a good 3D model. 

Check the images below for the correct 
shooting movements, depending on the type of 
the object and scene you want to acquire.


Source: [http://www.agisoft.com/pdf/tips_and_tricks/Image%20Capture%20Tips%20-
%20Equipment%20and%20Shooting%20Scenarios.pdf](http://www.agisoft.com/pdf/tips_and_tricks/Image%20Capture%20Tips%20-
%20Equipment%20and%20Shooting%20Scenarios.pdf)


## Tips for acquisition

- Capture images with good texture.
- Avoid completely texture-less, 
transparent and reflective images. 
The computer will have difficulty 
finding and matching features.
- If the scene does not contain 
enough texture itself, you could 
place additional background objects, 
such as posters, etc.




